export const LOAD_TITLES_SUCCESS = 'LOAD_TITLES_SUCCESS';
export const LOAD_PROGRESS_SUCCESS = 'LOAD_PROGRESS_SUCCESS';

export const SAVE_PLAYTHROUGH_SUCCESS = 'SAVE_PLAYTHROUGH_SUCCESS';
export const LOAD_PLAYTHROUGHS_SUCCESS = 'LOAD_PLAYTHROUGHS_SUCCESS';
export const DELETE_PLAYTHROUGH_SUCCESS = 'DELETE_PLAYTHROUGH_SUCCESS';
